### https://www.jenkins.io/doc/book/installing/docker/
### https://plugins.jenkins.io/configuration-as-code/

services:
  jenkins:
    container_name: jenkins
    build: ./compose/
    environment:
      DOCKER_HOST: unix:///var/run/docker.sock
      CASC_JENKINS_CONFIG: /var/jenkins_home/config_as_code/
    ports:
      - 8080:8080 ### HTTP
      - 50000:50000 ### Inbound Jenkins agents
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config_as_code/:/var/jenkins_home/config_as_code/
    networks:
      - jenkins
    restart: always

volumes:
  jenkins_data:
    name: jenkins_data

networks:
  jenkins:
    driver: bridge
