### https://www.jenkins.io/doc/book/installing/docker/
### https://www.cloudbees.com/blog/how-to-install-and-run-jenkins-with-docker-compose

services:
  jenkins:
    container_name: jenkins
    # image: jenkins/jenkins:2.430-jdk21
    build: .
    privileged: true
    # user: root
    environment:
      DOCKER_TLS_CERTDIR: /certs
    ports:
      # - 2376:2376 ### Expose host docker daemon to Jenkins
      - 8080:8080 ### HTTP
      - 50000:50000 ###
    volumes:
      - certs:/certs/client
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
    restart: always

volumes:
  certs:
    # driver: overlay2
  jenkins:
    # driver: overlay2

networks:
  jenkins:
    driver: bridge
