jobs:
  # - script: >
  #     multibranchPipelineJob('homelab_jenkins_test') {
  #       displayName('homelab_jenkins_test')
  #       branchSources {
  #         github {
  #           // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
  #           id('jasongalea123123') // IMPORTANT: use a constant and unique identifier
  #           // scanCredentialsId('github')
  #           repoOwner('jason-galea')
  #           repository('homelab_jenkins')
  #           // apiUri('http://my-github-server/api/v3') // Optional, needed for private github enterprise servers
  #         }
  #       }
  #       orphanedItemStrategy {
  #         discardOldItems {
  #           numToKeep(1)
  #         }
  #       }
  #       triggers {
  #         periodic(5)
  #       }
  #     }
  - script: >
      multibranchPipelineJob('homelab_jenkins_test') {
        displayName('Homelab Jenkins - Test Pipeline')
        branchSources {
          github {
            // The id option in the Git and GitHub branch source contexts is now mandatory (JENKINS-43693).
            id('n98w7zy3n5dk87wzt3fgk4d8zq') // IMPORTANT: use a constant and unique identifier
            // scanCredentialsId('github') // Public repo
            repoOwner('jason-galea')
            repository('homelab_jenkins')
            // apiUri('http://my-github-server/api/v3') // Optional, needed for private github enterprise servers
          }
        }
        orphanedItemStrategy {
          discardOldItems {
            numToKeep(1)
          }
        }
        triggers {
          periodic(5)
        }
        factory {
          workflowBranchProjectFactory {
            scriptPath("pipelines/homelab_jenkins_test.groovy")
          }
        }
      }

